export const ENDPOINT_URLS = {
  BASE_URL: "https://b2pshop.click/api/v2/",
  DEFAULT_TYPE: "/default-size",
  TYPES: "/directory/type-size?limit=number&offset=number&term=string",
  CATEGORIES: "/directory/categories",
  BUYERS_BY_TYPE:
    "/shops?type_size_id=string&limit=number&page=number&categories_id=string",
  BUYERS_WITH_ID_BY_NAME: "/shop/find-by-name?term=string",
  BUYERS_SIMILAR: "/shop/similar?shops=string",
  BUYER_BY_ID: "/shop/{shop_id}",
  BUYER_BY_ID_WITH_AUTH: "shop/{shop_id}",
  PRODUCTS_BY_BUYER_ID:
    "/shop/{shop_id}/products?type_size_id=string&locations_id=string&limit=number&page=number&sort=string",
  REVIEWS_BY_BUYER_ID:
    "/shop/{shop_id}/reviews?sort=string&limit=number&page=number",
  PRODUCT_BY_ID: "/product/{product_id}",
  PRODUCT_BY_ID_WITH_AUTH: "product/{product_id}",
  SIZES_BY_TYPE_ID:
    "/directory/type-size/{type_id}/sizes?limit=number&offset=number&term=string",
  STORIES: "/stories?limit=number&page=number",
  BRANDS: "/directory/stores",
  CONFIG: "/config",
  HOME_SLIDERS: "/main-page/slides",
  RECOMMEND_PRODUCTS: "/product/recommend?type_size_id=string",
  INSTRUCTIONS: "/instructions",
  DELIVERY_TYPES: "/delivery/types",
  SEARCH:
    "/search?type_size_id=string&locations_id=string&category_id=string&stores_id=string&delivery_type_id=string&price_from=number&price_to=number&weight_from=number&weight_to=number&limit=number&offset=number&sort=string",
  REVIEWS_BY_PRODUCT_ID:
    "/product/{product_id}/reviews?limit=number&offset=number",
  TIP_STOCKS: "/tips/stocks",
  PRODUCT_STOCKS: "product/{product_id}/stocks",
  SIGNIN: "signin",
  ACCOUNT_LOGIN_CHECK: "account/login/check",
  SIGNUP: "signup",
  RECOVERY_TOKEN: "recovery-token",
  CHECK_TWO_FACTOR: "/two-factor?code=string&token=string",
  TEXT_RULES: "text/rules",
  ACCOUNT_DEFAULT_TYPE_SIZE: "account/default-type-size",
  TEXT_ABOUT: "text/about",
  BUYERS_FAVORITES: "favorites-shops",
  TEXT_PAYED_RULES: "text/payed-rules",
  CREATE_ORDER: "order",
  PAYMENT_SYSTEMS: "payment-systems",
  TIP_PAYMENT: "/tips/payment",
  TIP_PAYED: "/tips/payed",
  PAYMENT_TOPUP: "payment/{payment_system_id}",
  GET_PAYMENT: "payment/{payment_id}",
  PAYMENT_PAYED: "payment/{payment_id}/payed",
  PAYMENT_CANCEL: "payment/{payment_id}/cancel",
  PAYMENT_EXPIRED: "payment/{payment_id}/expired",
  ORDER_PAYED: "order/{order_id}/payed",
  ORDER_CANCEL: "order/{order_id}/cancel",
  ORDER_DONE: "order/{order_id}/done",
  ORDER_FEEDBACK: "order/{order_id}/feedback",
  ACCOUNT: "account",
  ACCOUNT_IMAGE: "account/image",
  ACCOUNT_PASSWORD: "account/password",
  FRESH: "fresh",
  STATS: "stats",
  ACCOUNT_TWO_FACTOR: "account/two-factor",
  ACCOUNT_TWO_FACTOR_ENABLE: "account/two-factor/enable",
  ACCOUNT_TWO_FACTOR_DISABLE: "account/two-factor/disable",
  GET_ORDERS: "order",
  GET_ORDER: "order/{order_id}",
  GET_PAYMENTS: "payment",
  BUYER_FAVORITE: "shop/{shop_id}/favorite-attach",
  BUYER_UNFAVORITE: "shop/{shop_id}/favorite-detach",
  PRODUCT_FAVORITE: "product/{product_id}/favorite",
  PRODUCTS_FAVORITED: "product/favorite",
  CHAT_TYPES: "chat/types",
  CHAT: "chat",
  MESSAGES: "chat/{chat_id}",
  CAHT_INFO: "chat/{chat_id}/info",
  CAHT_CHECK: "chat/updates",
  MENU: "menu",
  COUPON: "coupon",
  GET_COUPON: "coupon/{coupon_id}",
  PRODUCTS_COUPON: "coupon/{coupon_id}/products",
  CHECK_STOCK: "product/{stock_id}/check",
  TEXT_COUPON: "text/coupon",
  PASSWORD_RESET: "password-reset",
  REFRESH: "refresh",
  WALLET: "wallet",
  TIP_NETWORK_PROBLEM: "tips/network-problem",
  CHECK_HEALTH: "/",
};

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const LOCALSTORAGES = {
  HIDDEN_NOTIFICATION_IDS: "hiddenNotificationIds",
  STOCKS: "stocks",
  LAST_SEARCH_STATE: "lastSearchState",
  FILTEROPTION: "filterOption",
  STOCKDATA: "stockData",
  USER: "user",
  START_STORY: "startStory",
  INTERVAL_BALANCE: "balanceInterval",
  INTERVAL_PAYMENT: "paymentInterval",
  INTERVAL_MESSAGE: "message_update_interval",
  FRESHED: "freshed",
  LAST_BUYER_SEARCH_KEYWORD: "lastBuyerSearchKeyword",
  SEARCH_LEAVE_PRODUCT_ID: "searchLeaveProductId",
  MENU: "menu",
  TEXT_LOST_NETWORK: "textLostNetwork",
};
